name: Publish Packages on Version Change

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  # Required for the `old-site` app to build
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  GH_PAT: ${{ secrets.GH_PAT }}
  PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
  # Required for the `website` package to build
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Install Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 20

    - name: Install Rush
      run: pnpm install -g @microsoft/rush

    - name: Install native build deps for node-canvas
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

    - name: Install dependencies
      run: rush install

    - name: Build packages
      run: NODE_ENV=production rush build

    - name: Publish to npmjs Package Registry
      run: |
        rush publish --publish --include-all --registry https://registry.npmjs.org/
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Publish to GitHub Package Registry
      run: |
        rush publish --publish --include-all --registry https://npm.pkg.github.com/
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
        GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
